### ISSUE TITLE
Migrate to Java 8

### ISSUE THREAD

**Issue by kpavlov** [kpavlov/fixio#12]
I'd love to migrate to java 8 but somebody may still use jdk 7 for production.

End of Java 7 Public Updates is April 2015

**If somebody is using Java 7, please give rise a voice!**

**Comment by kpavlov** [comment]
Someone is still using Java 6 , BTW
E.g. Gavin, (@GLitchfield) https://github.com/barchart/fixio/ (https://github.com/barchart/fixio/commit/27605f3b5cc27dccf272feebed8ca9e68e39ef0b)

**Comment by guidomedina** [comment]
You could have versions for example and make 1.0.x be Java 6, 1.1.x Java 7 and 2.x for Java 8 so that you can port back fixes and functionalities, though to be honest migrating from Java 6 to Java 7 shouldn't be straight forward, even having your projects still configured for Java 6 but use Java 7 VM to run them.

**Comment by kpavlov** [comment]
Master has migrated to java8
Java 7 and java 6 branches created (with limited support)
